      CREATE INDEX [IX_AgentPoolQueues_PoolId] ON [AgentPoolQueues] ([PoolId]);
      CREATE UNIQUE INDEX [IX_BuildAuthorizationScopes_Name] ON [BuildAuthorizationScopes] ([Name]);
      CREATE INDEX [IX_BuildConfigurations_BuildDefinitionId] ON [BuildConfigurations] ([BuildDefinitionId]);
      CREATE INDEX [IX_BuildConfigurations_BuildId] ON [BuildConfigurations] ([BuildId]);
      CREATE INDEX [IX_BuildConfigurations_ProjectId] ON [BuildConfigurations] ([ProjectId]);
      CREATE INDEX [IX_BuildConfigurations_RepositoryId] ON [BuildConfigurations] ([RepositoryId]);
      CREATE UNIQUE INDEX [IX_BuildDefinitionQualities_Name] ON [BuildDefinitionQualities] ([Name]);
      CREATE UNIQUE INDEX [IX_BuildDefinitionQueueStatuses_Name] ON [BuildDefinitionQueueStatuses] ([Name]);
      CREATE UNIQUE INDEX [IX_BuildDefinitionTypes_Name] ON [BuildDefinitionTypes] ([Name]);
      CREATE INDEX [IX_BuildDefinitionVariables_BuildDefinitionId] ON [BuildDefinitionVariables] ([BuildDefinitionId]);
      CREATE INDEX [IX_BuildIssues_BuildId] ON [BuildIssues] ([BuildId]);
      CREATE INDEX [IX_BuildIssues_IssueTypeId] ON [BuildIssues] ([IssueTypeId]);
      CREATE UNIQUE INDEX [IX_BuildIssueTypes_Name] ON [BuildIssueTypes] ([Name]);
      CREATE INDEX [IX_BuildLogs_BuildId] ON [BuildLogs] ([BuildId]);
      CREATE INDEX [IX_BuildProperties_BuildId] ON [BuildProperties] ([BuildId]);
      CREATE UNIQUE INDEX [IX_BuildQueuePriorities_Name] ON [BuildQueuePriorities] ([Name]);
      CREATE UNIQUE INDEX [IX_BuildReasons_Name] ON [BuildReasons] ([Name]);
      CREATE UNIQUE INDEX [IX_BuildRepository_BuildDefinitionId] ON [BuildRepository] ([BuildDefinitionId]);
      CREATE INDEX [IX_BuildRepository_GitRepositoryId] ON [BuildRepository] ([GitRepositoryId]);
      CREATE UNIQUE INDEX [IX_BuildResults_Name] ON [BuildResults] ([Name]);
      CREATE INDEX [IX_Builds_BuildRepositoryId] ON [Builds] ([BuildRepositoryId]);
      CREATE INDEX [IX_Builds_QueueId] ON [Builds] ([QueueId]);
      CREATE INDEX [IX_Builds_QueuePriorityId] ON [Builds] ([QueuePriorityId]);
      CREATE INDEX [IX_Builds_ReasonId] ON [Builds] ([ReasonId]);
      CREATE INDEX [IX_Builds_ResultId] ON [Builds] ([ResultId]);
      CREATE INDEX [IX_Builds_StatusId] ON [Builds] ([StatusId]);
      CREATE INDEX [IX_Builds_TriggeredByBuildId] ON [Builds] ([TriggeredByBuildId]);
      CREATE UNIQUE INDEX [IX_Builds_BuildDefinitionId_BuildNumber] ON [Builds] ([BuildDefinitionId], [BuildNumber]);
      CREATE UNIQUE INDEX [IX_BuildStatuses_Name] ON [BuildStatuses] ([Name]);
      CREATE UNIQUE INDEX [IX_BuildTriggers_BuildDefinitionId] ON [BuildTriggers] ([BuildDefinitionId]);
      CREATE INDEX [IX_BuildTriggers_TriggerTypeId] ON [BuildTriggers] ([TriggerTypeId]);
      CREATE UNIQUE INDEX [IX_BuildTriggerTypes_Name] ON [BuildTriggerTypes] ([Name]);
      CREATE INDEX [IX_DefinitionProperties_BuildDefinitionId] ON [DefinitionProperties] ([BuildDefinitionId]);
      CREATE INDEX [IX_Definitions_DraftOfDefinitionId] ON [Definitions] ([DraftOfDefinitionId]);
      CREATE INDEX [IX_Definitions_JobAuthorizationScopeId] ON [Definitions] ([JobAuthorizationScopeId]);
      CREATE INDEX [IX_Definitions_ProjectId] ON [Definitions] ([ProjectId]);
      CREATE INDEX [IX_Definitions_QualityId] ON [Definitions] ([QualityId]);
      CREATE INDEX [IX_Definitions_QueueId] ON [Definitions] ([QueueId]);
      CREATE INDEX [IX_Definitions_QueueStatusId] ON [Definitions] ([QueueStatusId]);
      CREATE INDEX [IX_Definitions_TypeId] ON [Definitions] ([TypeId]);
      CREATE UNIQUE INDEX [IX_Definitions_Name_ProjectId] ON [Definitions] ([Name], [ProjectId]);
      CREATE INDEX [IX_GitRepositories_ParentRepositoryId] ON [GitRepositories] ([ParentRepositoryId]);
      CREATE INDEX [IX_GitRepositories_ProjectId] ON [GitRepositories] ([ProjectId]);
      CREATE INDEX [IX_Projects_StateId] ON [Projects] ([StateId]);
      CREATE INDEX [IX_Projects_VisibilityId] ON [Projects] ([VisibilityId]);
      CREATE UNIQUE INDEX [IX_Projects_Name_OrganizationName] ON [Projects] ([Name], [OrganizationName]);
      CREATE UNIQUE INDEX [IX_ProjectStates_Name] ON [ProjectStates] ([Name]);
      CREATE UNIQUE INDEX [IX_ProjectVisibilities_Name] ON [ProjectVisibilities] ([Name]);
      CREATE UNIQUE INDEX [IX_TaskResults_Name] ON [TaskResults] ([Name]);
      CREATE INDEX [IX_TestActionResults_TestResultIterationId] ON [TestActionResults] ([TestResultIterationId]);
      CREATE INDEX [IX_TestPlans_BuildDefinitionId] ON [TestPlans] ([BuildDefinitionId]);
      CREATE INDEX [IX_TestPlans_BuildId] ON [TestPlans] ([BuildId]);
      CREATE INDEX [IX_TestPlans_PreviousBuildId] ON [TestPlans] ([PreviousBuildId]);
      CREATE INDEX [IX_TestPlans_ProjectId] ON [TestPlans] ([ProjectId]);
      CREATE INDEX [IX_TestPlans_RootSuiteId] ON [TestPlans] ([RootSuiteId]);
      CREATE INDEX [IX_TestPlanVariables_ProjectID] ON [TestPlanVariables] ([ProjectID]);
      CREATE INDEX [IX_TestPlanVariables_TestPlanId] ON [TestPlanVariables] ([TestPlanId]);
      CREATE INDEX [IX_TestResultAttachments_TestResultId] ON [TestResultAttachments] ([TestResultId]);
      CREATE INDEX [IX_TestResultCustomFields_TestResultId] ON [TestResultCustomFields] ([TestResultId]);
      CREATE UNIQUE INDEX [IX_TestResultFailureTypes_Name] ON [TestResultFailureTypes] ([Name]);
      CREATE UNIQUE INDEX [IX_TestResultGroupTypes_Name] ON [TestResultGroupTypes] ([Name]);
      CREATE INDEX [IX_TestResultIterationDetails_TestResultId] ON [TestResultIterationDetails] ([TestResultId]);
      CREATE INDEX [IX_TestResults_AfnStripId] ON [TestResults] ([AfnStripId]);
      CREATE INDEX [IX_TestResults_BuildId] ON [TestResults] ([BuildId]);
      CREATE INDEX [IX_TestResults_FailureTypeId] ON [TestResults] ([FailureTypeId]);
      CREATE INDEX [IX_TestResults_GroupTypeId] ON [TestResults] ([GroupTypeId]);
      CREATE INDEX [IX_TestResults_ProjectId] ON [TestResults] ([ProjectId]);
      CREATE INDEX [IX_TestResults_TestRunId] ON [TestResults] ([TestRunId]);
      CREATE INDEX [IX_TestResults_TestRunStateId] ON [TestResults] ([TestRunStateId]);
      CREATE INDEX [IX_TestResults_TestSuiteId] ON [TestResults] ([TestSuiteId]);
      CREATE INDEX [IX_TestRunAttachments_TestRunId] ON [TestRunAttachments] ([TestRunId]);
      CREATE INDEX [IX_TestRunCustomFields_TestRunId] ON [TestRunCustomFields] ([TestRunId]);
      CREATE INDEX [IX_TestRuns_BuildConfigurationId] ON [TestRuns] ([BuildConfigurationId]);
      CREATE INDEX [IX_TestRuns_BuildId] ON [TestRuns] ([BuildId]);
      CREATE INDEX [IX_TestRuns_ProjectId] ON [TestRuns] ([ProjectId]);
      CREATE INDEX [IX_TestRuns_StateId] ON [TestRuns] ([StateId]);
      CREATE INDEX [IX_TestRuns_SubstateId] ON [TestRuns] ([SubstateId]);
      CREATE INDEX [IX_TestRuns_TestPlanId] ON [TestRuns] ([TestPlanId]);
      CREATE UNIQUE INDEX [IX_TestRunStates_Name] ON [TestRunStates] ([Name]);
      CREATE INDEX [IX_TestRunStatistics_TestRunId] ON [TestRunStatistics] ([TestRunId]);
      CREATE UNIQUE INDEX [IX_TestRunSubstates_Name] ON [TestRunSubstates] ([Name]);
      CREATE INDEX [IX_TestRunTags_TestRunId] ON [TestRunTags] ([TestRunId]);
      CREATE INDEX [IX_TestSuite_ParentTestSuiteId] ON [TestSuite] ([ParentTestSuiteId]);
      CREATE INDEX [IX_TestSuite_ProjectId] ON [TestSuite] ([ProjectId]);
      CREATE INDEX [IX_TestSuite_SuiteTypeId] ON [TestSuite] ([SuiteTypeId]);
      CREATE INDEX [IX_TestSuite_TestPlanId] ON [TestSuite] ([TestPlanId]);
      CREATE UNIQUE INDEX [IX_TestSuiteType_Name] ON [TestSuiteType] ([Name]);
      CREATE INDEX [IX_TimelineAttempts_RecordId] ON [TimelineAttempts] ([RecordId]);
      CREATE INDEX [IX_TimelineAttempts_TimelineId] ON [TimelineAttempts] ([TimelineId]);
      CREATE INDEX [IX_TimelineRecords_LogId] ON [TimelineRecords] ([LogId]);
      CREATE INDEX [IX_TimelineRecords_ParentId] ON [TimelineRecords] ([ParentId]);
      CREATE INDEX [IX_TimelineRecords_ResultId] ON [TimelineRecords] ([ResultId]);
      CREATE INDEX [IX_TimelineRecords_StateId] ON [TimelineRecords] ([StateId]);
      CREATE INDEX [IX_TimelineRecords_TimelineId] ON [TimelineRecords] ([TimelineId]);
      CREATE UNIQUE INDEX [IX_TimelineRecordStates_Name] ON [TimelineRecordStates] ([Name]);
      CREATE INDEX [IX_Timelines_BuildId] ON [Timelines] ([BuildId]);
      ALTER TABLE [TestRuns] ADD CONSTRAINT [FK_TestRuns_TestPlans_TestPlanId] FOREIGN KEY ([TestPlanId]) REFERENCES [TestPlans] ([Id]) ON DELETE NO ACTION;
      ALTER TABLE [TestPlans] ADD CONSTRAINT [FK_TestPlans_TestSuite_RootSuiteId] FOREIGN KEY ([RootSuiteId]) REFERENCES [TestSuite] ([Id]) ON DELETE NO ACTION;
      ALTER TABLE [TestResults] ADD CONSTRAINT [FK_TestResults_TestResultAttachments_AfnStripId] FOREIGN KEY ([AfnStripId]) REFERENCES [TestResultAttachments] ([Id]) ON DELETE NO ACTION;